# Generated by Django 6.0 on 2026-02-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_disease_doctor_remove_healthstatistics_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
                ('dose', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='drugprescription',
            name='drug_dose',
        ),
        migrations.RemoveField(
            model_name='drugprescription',
            name='drug_title',
        ),
        migrations.AddField(
            model_name='drugprescription',
            name='drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.drug'),
        ),
    ]
