# Generated by Django 6.0 on 2026-02-04 10:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_is_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, validators=[app.models.validate_pass]),
        ),
    ]
