# Generated by Django 6.0 on 2026-02-04 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthstatistics',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
